/*
 * MainWindow.java
 *
 * Created on Oct 21, 2009, 10:46:35 AM
 */
package ampt.ui;

import ampt.core.devices.ChordFilterDevice;
import ampt.ui.canvas.ChordFilterBox;
import ampt.ui.canvas.KeyboardBox;
import ampt.ui.canvas.MidiDeviceBox;
import ampt.ui.canvas.MidiDeviceButton;
import ampt.ui.keyboard.KeyboardDevice;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.MidiDevice;
import javax.sound.midi.MidiDevice.Info;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.JOptionPane;

/**
 * This is the main window for the GUI.  It contains a split pane, in which the
 * top contains any tabs that are desired, such as the canvas and the software
 * keyboard.  The bottom contains a console for any desired output.
 *
 * @author Christopher Redding
 */
public class MainWindow extends JFrame {

    /*
     * This is used for listening for the user clicking on the canvas panel so
     * the user can place a filter after choosing the filter from the Toolbar.
     *
     * NOTE: For some reason, Netbeans places all of the class variables at the
     * bottom of the file, so look there for any other variables you want to
     * see.
     */
    private MouseAdapter canvasButtonMouseAdapter = null;

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     *
     * I have modified this method to insert all of the devices obtained from
     * calling MidiSystem.getDeviceInfo() as a button in the toolbar.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvasToolbar1 = new ampt.ui.canvas.CanvasToolbar();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        canvasToolbar2 = new ampt.ui.canvas.CanvasToolbar();
        jPanel2 = new javax.swing.JPanel();
        canvasPanel1 = new ampt.ui.canvas.CanvasPanel();
        jPanel3 = new javax.swing.JPanel();
        metronomePanel1 = new ampt.examples.MetronomePanel();
        filterPropertiesPanel1 = new ampt.ui.canvas.FilterPropertiesPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();

        canvasToolbar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Additive MIDI Performance Tool");

        jSplitPane1.setBorder(null);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);

        canvasToolbar2.setBorder(javax.swing.BorderFactory.createTitledBorder("Canvas Toolbar"));
        canvasToolbar2.setFloatable(false);
        canvasToolbar2.setOrientation(1);
        canvasToolbar2.setRollover(true);

        Info[] deviceInfos = MidiSystem.getMidiDeviceInfo();
        for(Info deviceInfo: deviceInfos){
            MidiDeviceButton button = new MidiDeviceButton(deviceInfo);
            canvasToolbar2.add(button);
            button.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ButtonHandler(evt);
                }
            });
        }

        //ChordFilterButton chordButton = new ChordFilterButton();
        //canvasToolbar2.add(chordButton);
        //chordButton.addActionListener(new java.awt.event.ActionListener() {
            //            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //                ButtonHandler(evt);
                //            }
            //        });

    jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Canvas"));

    canvasPanel1.setBackground(new java.awt.Color(255, 255, 255));

    javax.swing.GroupLayout canvasPanel1Layout = new javax.swing.GroupLayout(canvasPanel1);
    canvasPanel1.setLayout(canvasPanel1Layout);
    canvasPanel1Layout.setHorizontalGroup(
        canvasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 234, Short.MAX_VALUE)
    );
    canvasPanel1Layout.setVerticalGroup(
        canvasPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 185, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(canvasPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(canvasPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    metronomePanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Metronome"));

    filterPropertiesPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter Properties"));

    javax.swing.GroupLayout filterPropertiesPanel1Layout = new javax.swing.GroupLayout(filterPropertiesPanel1);
    filterPropertiesPanel1.setLayout(filterPropertiesPanel1Layout);
    filterPropertiesPanel1Layout.setHorizontalGroup(
        filterPropertiesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 189, Short.MAX_VALUE)
    );
    filterPropertiesPanel1Layout.setVerticalGroup(
        filterPropertiesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 114, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(metronomePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
        .addComponent(filterPropertiesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(metronomePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(filterPropertiesPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(canvasToolbar2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(canvasToolbar2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    jTabbedPane1.addTab("Canvas", jPanel1);

    jSplitPane1.setLeftComponent(jTabbedPane1);

    jScrollPane1.setPreferredSize(new java.awt.Dimension(24, 200));

    jTextPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Console"));
    jTextPane1.setEditable(false);
    jScrollPane1.setViewportView(jTextPane1);

    jSplitPane1.setRightComponent(jScrollPane1);

    fileMenu.setText("File");
    jMenuBar1.add(fileMenu);

    editMenu.setText("Edit");
    jMenuBar1.add(editMenu);

    viewMenu.setText("View");

    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        JMenuItem item = new JMenuItem(info.getName());

        item.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                viewMenuHandler(evt);
            }
        });

        viewMenu.add(item);
    }

    jMenuBar1.add(viewMenu);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    private void viewMenuHandler(ActionEvent event){
        JMenuItem source = (JMenuItem) event.getSource();
        String lookAndFeelName = source.getText();
        for(LookAndFeelInfo info: UIManager.getInstalledLookAndFeels()){
            if(lookAndFeelName.equals(info.getName())){
                try{
                    UIManager.setLookAndFeel(info.getClassName());
                    SwingUtilities.updateComponentTreeUI(this);
                    this.pack();
                } catch (Exception ex){
                    ex.printStackTrace();
                }
            }
        }
    }

    /**
     * A button handler for all of the buttons on the toolbar.  This method
     * registers a mouse adapter on the canvas so the box that represents a
     * MidiDevice or a filter can be placed on the canvas.
     * @param evt
     */
    private void ButtonHandler(ActionEvent evt) {
        // TODO add your handling code here:
        final Object source = evt.getSource();
        if (canvasButtonMouseAdapter != null) {
            canvasPanel1.removeMouseListener(canvasButtonMouseAdapter);
        }

        canvasButtonMouseAdapter = new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                canvasPanel1.removeMouseListener(this);
                Point point = e.getPoint();
                if (source instanceof MidiDeviceButton) {
                    try {
                        MidiDeviceButton deviceButton = (MidiDeviceButton) source;
                        MidiDevice device = MidiSystem.getMidiDevice(deviceButton.getDeviceInfo());
                        MidiDeviceBox box = null;
                        if (device instanceof KeyboardDevice) {
                            KeyboardDevice keyboard = (KeyboardDevice) device;
                            box = new KeyboardBox(keyboard);
                        } else if (device instanceof ChordFilterDevice) {
                            ChordFilterDevice chordDevice = (ChordFilterDevice) device;
                            box = new ChordFilterBox(chordDevice);
                        } else {
                            box = new MidiDeviceBox(device);
                        }
                        canvasPanel1.add(box);
                        box.setLocation(point);
                        box.setSize(box.getPreferredSize());
                        box.validate();
                        canvasPanel1.repaint();
                    } catch (MidiUnavailableException ex) {

                        JOptionPane.showMessageDialog(null,
                                "Unable to add device  to canvas. " + ex.getLocalizedMessage(),
                                "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        };
        canvasPanel1.addMouseListener(canvasButtonMouseAdapter);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ampt.ui.canvas.CanvasPanel canvasPanel1;
    private ampt.ui.canvas.CanvasToolbar canvasToolbar1;
    private ampt.ui.canvas.CanvasToolbar canvasToolbar2;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private ampt.ui.canvas.FilterPropertiesPanel filterPropertiesPanel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private ampt.examples.MetronomePanel metronomePanel1;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
