/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ampt_core_time_NativeWinClock */

#ifndef _Included_ampt_core_time_NativeWinClock
#define _Included_ampt_core_time_NativeWinClock
#ifdef __cplusplus
extern "C" {
#endif
#undef ampt_core_time_NativeWinClock_UNIT_SECONDS
#define ampt_core_time_NativeWinClock_UNIT_SECONDS 1L
#undef ampt_core_time_NativeWinClock_UNIT_MILLIS
#define ampt_core_time_NativeWinClock_UNIT_MILLIS 1000L
#undef ampt_core_time_NativeWinClock_UNIT_MICROS
#define ampt_core_time_NativeWinClock_UNIT_MICROS 1000000L
#undef ampt_core_time_NativeWinClock_UNIT_NANOS
#define ampt_core_time_NativeWinClock_UNIT_NANOS 1000000000L
/*
 * Class:     ampt_core_time_NativeWinClock
 * Method:    getFrequency
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ampt_core_time_NativeWinClock_getFrequency
  (JNIEnv *, jobject);

/*
 * Class:     ampt_core_time_NativeWinClock
 * Method:    getCounter
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ampt_core_time_NativeWinClock_getCounter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
