/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CanvasToolbar.java
 *
 * Created on Oct 21, 2009, 11:06:46 AM
 */

package ampt.ui.canvas;

import javax.swing.JToolBar;

/**
 *
 * @author Christopher
 */
public class CanvasToolbar extends JToolBar {

    /** Creates new form BeanForm */
    public CanvasToolbar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
