/*
 * MetronomePanel.java
 *
 * Created on Nov 10, 2009, 5:54:23 PM
 */

package ampt.examples;

/**
 *
 * @author robert
 */
public class MetronomePanel extends javax.swing.JPanel {

    /** Creates new form MetronomePanel */
    public MetronomePanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        animatedMetronome1 = new ampt.examples.AnimatedMetronome();
        toggleMetronomeBtn = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(175, 50));

        animatedMetronome1.setMaximumSize(new java.awt.Dimension(28, 90));

        javax.swing.GroupLayout animatedMetronome1Layout = new javax.swing.GroupLayout(animatedMetronome1);
        animatedMetronome1.setLayout(animatedMetronome1Layout);
        animatedMetronome1Layout.setHorizontalGroup(
            animatedMetronome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
        );
        animatedMetronome1Layout.setVerticalGroup(
            animatedMetronome1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        toggleMetronomeBtn.setText("On");
        toggleMetronomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleMetronomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(animatedMetronome1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toggleMetronomeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toggleMetronomeBtn)
                    .addComponent(animatedMetronome1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toggleMetronomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleMetronomeBtnActionPerformed
        if (!toggleMetronomeBtn.isSelected()) {
            animatedMetronome1.stop();
            toggleMetronomeBtn.setText("Start");
        } else {
            animatedMetronome1.start();
            toggleMetronomeBtn.setText("Stop");
        }
    }//GEN-LAST:event_toggleMetronomeBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ampt.examples.AnimatedMetronome animatedMetronome1;
    private javax.swing.JToggleButton toggleMetronomeBtn;
    // End of variables declaration//GEN-END:variables

}
